import type { NextPage } from "next";
import Head from "next/head";

const languaje = "es";

const multiLingualPage = {
  es: {
    titlePage: "Contacto",
  },
  en: {
    titlePage: "Contact",
  },
};

const multiLingualContact = {
  es: {
    titleContact: "Contactame",
    youCanContact:
      "Puedes escribirme por cualquiera de estos medios, apenas vea tu mensaje te constestaré",
  },
  en: {
    titleContact: "Contact me",
    youCanContact:
      "You can write me by any of these ways, as soon as I see your message I will answer you",
  },
};

const ContactPage: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>
          Miguelangel Parra - {multiLingualPage[languaje].titlePage}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">{multiLingualContact[languaje].titleContact}</h1>
        <p>{multiLingualContact[languaje].youCanContact}</p>

        <ul>
          <li>
            Mail: {" "} 
            <a href="mailto:miguelangel.parradavila@outlook.com?Subject=I%20write%20from%20miguelangelparra.com">
              miguelangel.parradavila@outlook.com
            </a>
          </li>
          <li>
            Twitter:{" "} 
            <a href="https://twitter.com/migpsi" target="_blank" rel="noopener noreferrer">
              @migpsi
            </a>
          </li>
        </ul>
      </main>
    </div>
  );
};

export default ContactPage;
