import type { NextPage } from "next";
import Head from "next/head";

const languaje = "es";

const multiLingualPage = {
  es: {
    titlePage: "Curriculum Vitae (CV)",
  },
  en: {
    titlePage: "Contact",
  },
};

const multiLingualContact = {
  es: {
    titleContact: "CV",
    youCanContact:
      "Puedes escribirme por cualquiera de estos medios, apenas vea tu mensaje te constestaré",
  },
  en: {
    titleContact: "Contact me",
    youCanContact:
      "You can write me by any of these ways, as soon as I see your message I will answer you",
  },
};

const CVPage: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>
          Miguelangel Parra - {multiLingualPage[languaje].titlePage}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">{multiLingualContact[languaje].titleContact}</h1>

     
     
     <div className="card">
      <h4>Mi experiencia 1 </h4>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Inventore excepturi impedit unde porro aspernatur consequuntur adipisci quae quaerat, nobis atque! Atque quo assumenda esse at reiciendis aliquid iste aut tempora!</p>
     </div>

     <div className="card">
      <h4>Mi experiencia 1 </h4>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Inventore excepturi impedit unde porro aspernatur consequuntur adipisci quae quaerat, nobis atque! Atque quo assumenda esse at reiciendis aliquid iste aut tempora!</p>
     </div>

     <div className="card">
      <h4>Mi experiencia 1 </h4>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Inventore excepturi impedit unde porro aspernatur consequuntur adipisci quae quaerat, nobis atque! Atque quo assumenda esse at reiciendis aliquid iste aut tempora!</p>
     </div>

     <div className="card">
      <h4>Mi experiencia 1 </h4>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Inventore excepturi impedit unde porro aspernatur consequuntur adipisci quae quaerat, nobis atque! Atque quo assumenda esse at reiciendis aliquid iste aut tempora!</p>
     </div>

     <div className="card">
      <h4>Mi experiencia 1 </h4>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Inventore excepturi impedit unde porro aspernatur consequuntur adipisci quae quaerat, nobis atque! Atque quo assumenda esse at reiciendis aliquid iste aut tempora!</p>
     </div>

     <div className="card">
      <h4>Mi experiencia 1 </h4>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Inventore excepturi impedit unde porro aspernatur consequuntur adipisci quae quaerat, nobis atque! Atque quo assumenda esse at reiciendis aliquid iste aut tempora!</p>
     </div>

      </main>
    </div>
  );
};

export default CVPage;
