import type { NextPage } from "next";
import Head from "next/head";

const languaje = "es";

const multiLingualPage = {
  es: {
    titlePage: "Sobre mi",
  },
  en: {
    titlePage: "About me",
  },
};

const multiLingualContact = {
  es: {
    titleContact: "Te cuento sobre mi",
    youCanContact:
      "Puedes escribirme por cualquiera de estos medios, apenas vea tu mensaje te constestaré",
  },
  en: {
    titleContact: "I talk you about me",
    youCanContact:
      "You can write me by any of these ways, as soon as I see your message I will answer you",
  },
};

const AboutPage: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>
          Miguelangel Parra - {multiLingualPage[languaje].titlePage}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">{multiLingualContact[languaje].titleContact}</h1>
        <p>Pronto te contaré más sobre mi...</p>
      </main>
    </div>
  );
};

export default AboutPage;
